SELECT SEQ,FECHAHORA,RECTYPE,D1,D2,D3 FROM RAWDATA
WHERE RECTYPE IN ('PRESURE','EXE') OR D1 IN ('MICARDIS','TAROPREN')



SELECT FECHAHORA,RECTYPE,COALESCE(D1,''),COALESCE(D2,''),COALESCE(D3,'') 
FROM RAWDATA
WHERE (RECTYPE IN ('PRESURE','EXE') OR D1 IN ('MICARDIS','TAROPREN'))
and (datepart(hour,fechahora)*60 + datepart(minute,fechahora) <= 720 )
AND FECHAHORA > CONVERT(DATETIME,'2019/8/1')
ORDER BY FECHAHORA


SELECT FECHAHORA,RECTYPE,COALESCE(D1,''),COALESCE(D2,''),COALESCE(D3,'') 
FROM RAWDATA
WHERE (RECTYPE IN ('PRESURE','EXE') OR D1 IN ('MICARDIS','TAROPREN'))
and (datepart(hour,fechahora)*60 + datepart(minute,fechahora) > 720 )
AND FECHAHORA > CONVERT(DATETIME,'2019/8/1')
ORDER BY FECHAHORA




SELECT FECHAHORA,RECTYPE,COALESCE(D1,''),COALESCE(D2,''),COALESCE(D3,'') 
FROM RAWDATA
WHERE (RECTYPE IN ('WGT','EXE') )
AND FECHAHORA > CONVERT(DATETIME,'2019/8/1')
ORDER BY FECHAHORA


SELECT * FROM RAWDATA


SELECT SEQ,FECHAHORA,RECTYPE,D1,D2,D3 FROM RAWDATA
WHERE RECTYPE IN ('PRESURE','EXE')
ORDER BY FECHAHORA

select * from rawdata
WHERE ID = 3000

--INSERT INTO RAWDATA VALUES(3000,20190806,'15:37','8/6/2019 3:08:00 PM','PRESURE''75','72','walk ',NULL,NULL,NULL,NULL)








 